version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - echo Logging in to Docker Hub...
      - docker login --username <your_dockerhub_username> --password <your_dockerhub_password>
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Writing imagedefinitions.json for CodeDeploy...
      - printf '[{"name":"f2p-backend","imageUri":"%s"}]' $ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG > imagedefinitions.json
      - echo Updating kubeconfig for EKS cluster...
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME
      - echo Rendering and previewing deployment.yaml...
      - sed "s|IMAGE_URI|$ECR_REGISTRY/$REPO_NAME:$IMAGE_TAG|g" k8s/deployment.yaml > k8s/rendered-deployment.yaml
      - cat k8s/rendered-deployment.yaml
      - echo Deploying Kubernetes resources...
      - kubectl apply -f k8s/rendered-deployment.yaml
