apiVersion: v1
kind: Service
metadata:
  name: apache-webserver
  labels:
    app: apache-webserver
spec:
  type: LoadBalancer
  selector:
    app: apache-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
